# Generated by Django 2.2.2 on 2019-11-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='parent',
            field=models.IntegerField(default=1),
        ),
    ]
