# Generated by Django 2.2.2 on 2019-11-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_postcomments_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='postcomments',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='postlikes',
            old_name='user',
            new_name='user_id',
        ),
    ]
