# Generated by Django 2.2.7 on 2019-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20191121_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Polls', 'Polls'), ('Project', 'Project')], default='Post', max_length=50),
        ),
    ]
