# Generated by Django 2.2.2 on 2019-11-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20191108_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='activity',
            field=models.CharField(default='Liked', editable=False, max_length=200),
        ),
    ]
