# Generated by Django 2.2.7 on 2019-12-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20191205_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postshare',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posttag',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
