# Generated by Django 2.2.7 on 2019-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20191206_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='media_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
