# Generated by Django 2.2.2 on 2019-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20191111_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='post_media',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
