# Generated by Django 2.2.7 on 2019-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_postmedia_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='post_media',
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
