# Generated by Django 2.2.7 on 2019-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_postmedia_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
