# Generated by Django 2.2.7 on 2019-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_auto_20191112_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
