# Generated by Django 2.2.7 on 2019-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_auto_20191115_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='parent',
            field=models.IntegerField(default=-1),
        ),
    ]
