# Generated by Django 5.0.6 on 2024-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='events_banners/'),
        ),
    ]
