# Generated by Django 5.0.6 on 2024-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0002_company_banner_company_logo_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='service_banners/'),
        ),
    ]
