# Generated by Django 5.0.6 on 2024-05-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
