# Generated by Django 5.0.6 on 2024-05-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0004_company_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
