# Generated by Django 5.0.6 on 2024-05-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0006_company_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
    ]
