# Generated by Django 5.0.6 on 2024-05-27 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0011_events_leads_news_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='updted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 13:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companyprofile.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leads',
            name='updted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 13:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='updted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='updted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='long_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leads',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='long_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='long_desc',
            field=models.TextField(),
        ),
    ]
