# Generated by Django 5.0.6 on 2024-05-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0012_remove_leads_created_date_remove_leads_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='banner',
        ),
    ]
