# Generated by Django 5.0.6 on 2024-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0013_remove_events_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='updted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
