# Generated by Django 5.0.6 on 2024-05-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0014_alter_events_updted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updted_at',
        ),
    ]
