# Generated by Django 5.0.6 on 2024-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0015_remove_events_created_at_remove_events_updted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='updted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
