# Generated by Django 5.0.6 on 2024-05-27 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0016_alter_news_updted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='updted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
