# Generated by Django 5.0.6 on 2024-05-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0017_events_created_at_events_updted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_by',
        ),
    ]
