# Generated by Django 2.2.6 on 2019-11-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
