# Generated by Django 2.2.6 on 2019-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_is_mail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_mail_code',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
