# Generated by Django 2.2.7 on 2019-11-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_interests_languages_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interests',
            options={},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={},
        ),
        migrations.AlterModelTable(
            name='interests',
            table=None,
        ),
        migrations.AlterModelTable(
            name='languages',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skills',
            table=None,
        ),
    ]
