# Generated by Django 2.2.7 on 2019-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20191128_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
