# Generated by Django 2.2.7 on 2019-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_user_verify_mail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='session_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='session_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name='education',
            table=None,
        ),
        migrations.AlterModelTable(
            name='myprojects',
            table=None,
        ),
    ]
