# Generated by Django 2.2.7 on 2019-12-19 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_followers_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
