# Generated by Django 2.2.7 on 2019-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20191115_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylanguage',
            name='name',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myplaces',
            name='place_name',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='project_title',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='name',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
    ]
