# Generated by Django 2.2.7 on 2019-12-19 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20191219_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
