# Generated by Django 2.2.7 on 2019-11-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20191115_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplaces',
            name='from_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='myplaces',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
    ]
